//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialStream.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class socialstream_developmentEntities : DbContext
    {
        public socialstream_developmentEntities()
            : base("name=socialstream_developmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Post> Post { get; set; }
        public DbSet<Thread> Thread { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Log> Log { get; set; }
    }
}
